#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rabbitmq-c
Version  : 0.9.0
Release  : 3
URL      : https://github.com/alanxz/rabbitmq-c/archive/v0.9.0.tar.gz
Source0  : https://github.com/alanxz/rabbitmq-c/archive/v0.9.0.tar.gz
Summary  : An AMQP 0-9-1 client library
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: rabbitmq-c-bin = %{version}-%{release}
Requires: rabbitmq-c-lib = %{version}-%{release}
Requires: rabbitmq-c-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : popt-dev
BuildRequires : python3
BuildRequires : xmlto

%description
# RabbitMQ C AMQP client library
[![Build Status](https://secure.travis-ci.org/alanxz/rabbitmq-c.png?branch=master)](http://travis-ci.org/alanxz/rabbitmq-c)

%package bin
Summary: bin components for the rabbitmq-c package.
Group: Binaries
Requires: rabbitmq-c-license = %{version}-%{release}

%description bin
bin components for the rabbitmq-c package.


%package dev
Summary: dev components for the rabbitmq-c package.
Group: Development
Requires: rabbitmq-c-lib = %{version}-%{release}
Requires: rabbitmq-c-bin = %{version}-%{release}
Provides: rabbitmq-c-devel = %{version}-%{release}

%description dev
dev components for the rabbitmq-c package.


%package lib
Summary: lib components for the rabbitmq-c package.
Group: Libraries
Requires: rabbitmq-c-license = %{version}-%{release}

%description lib
lib components for the rabbitmq-c package.


%package license
Summary: license components for the rabbitmq-c package.
Group: Default

%description license
license components for the rabbitmq-c package.


%prep
%setup -q -n rabbitmq-c-0.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542420361
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1542420361
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rabbitmq-c
cp LICENSE-MIT %{buildroot}/usr/share/package-licenses/rabbitmq-c/LICENSE-MIT
cp cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/rabbitmq-c/cmake_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/amqp-consume
/usr/bin/amqp-declare-queue
/usr/bin/amqp-delete-queue
/usr/bin/amqp-get
/usr/bin/amqp-publish

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/librabbitmq.so
/usr/lib64/pkgconfig/librabbitmq.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/librabbitmq.so.4
/usr/lib64/librabbitmq.so.4.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rabbitmq-c/LICENSE-MIT
/usr/share/package-licenses/rabbitmq-c/cmake_COPYING-CMAKE-SCRIPTS
